:plugin-ver: 0.6.1
= SWAMP Jenkins Plugin
Jared Sweetland, Vamshi Basupalli, James A. Kupsch
{plugin-ver} {docdatetime}
:toc:
:numbered:

== Developing the Plugin

If you have installed the source code, you will need a few other repositories installed to make the plugin compile properly.
- Java-CLI (https://github.com/mirswamp/java-cli.git) (use the CLI-with-dependencies.jar file)
- Scarf-IO (https://github.com/mirswamp/swamp-scarf-io.git)

Once you have these, you can configure an eclipse project (or whatever IDE you plan to use) with the dependencies located in the .m2 directory.

To create the project in Eclipse:
- Download the github repository https://github.com/mirswamp/swamp-jenkins-plugin.git
- Go to file -> import -> maven -> existing maven projects
- Enter the SWAMP Plugin repository
- Click Next and Finish

To configure the project in Eclipse:
- Run maven install on both the github repositories listed above to install them to the proper directories
- Right click the project directory and click properties
- Go to the Java build path tab
- Click _Add External Jars_
- Enter ~/.m2/repository/org/continuousassurance/swamp/java-cli/1.0-SNAPSHOT/java-cli-1.0-SNAPSHOT-jar-with-dependencies.jar
- Click _OK_
- Repeat with ~/.m2/repository/org/continuousassurance/scarf-io/1.0-SNAPSHOT/scarf-io-1.0-SNAPSHOT.jar
If done correctly, (most) compiler errors should go away (there may be some extras relating to messages.java)

== Debugging the Plugin
To test any changes to the code:
- From the Plugin directory, run `mvn clean package -DskipTests -Dmaven.test.skip=true -Denforcer.skip=true`
- In your instance of Jenkins, go to Manage Jenkins -> Manage Plugins
- Select the _Advanced_ Tab
- Under *Upload Plugin* find the swamp.hpi file generated by your build command (should be the plugin directory/target/swamp.hpi)
- Click _Upload_
- NOTE: Every time a plugin is updated, you will need to restart Jenkins, so select the restart Jenkins checkbox and wait for a restart

Unfortunately, the Eclipse debugger does not work well with the plugin. Instead, you can use print statements where applicable to debug variables.

Using `System.out.print("your text");` will print to the console, where you ran java -jar for Jenkins. +
Using `logger.log("your text");` where applicable will print to the logger within the Jenkins build.

== Layout of the Source Code
Different elements of the plugin are located in different locations of the plugin, so here is a general list of where to look for certian errors:

=== Issues with logging in
The login function is located within the DescriptorImpl.java class, but is called in various locations of the DescriptorImpl.java, SwampPostBuild.java, and AssessmentInfo classes

=== Issues with package submission / assessment submission
This is all done in the bulk of SwampPostBuild.java within the perform function.

=== Issues with parsing data for output
The parsing is called at the end of the perform function within SwampPostBuild.java, but most of the code executed is in the SwampParser.java class in the parse function.

=== Issues with generating graphs
These issues may be a bit harder to fix because there are a lot of nested functions to make this work properly. Start with Restults.java and work back through method trees to try to find where your issue is.

If you would like to create a new graph, add it to the list of graphs returned from the bottom of SwampProjectAction.java
